### ISSUE TITLE
vue-til-server 사전 서버 실행시 error가 발생해요

### ISSUE THREAD

**Issue by noah6netguy** [joshua1988/2020-naver-vue#2]
움.. error가 발생해요.
- npm install시. 
```
naver@noah-macbook vue-til-server % sudo npm install

> fsevents@1.2.7 install /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/build'
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)

> bcrypt@3.0.5 install /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.5 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/build'
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/naver/.npm/_logs/2020-06-17T07_59_11_315Z-debug.log
naver@noah-macbook vue-til-server % k/Develop/Study_webpack/Tutorial_3/vue-til-server/node_modules/bcrypt/lib/binding
```
- npm run start시
```
naver@noah-macbook vue-til-server % sudo npm run start

> server@1.0.0 start /Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server
> node dist/app.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/naver/yooks_book/Develop/Study_webpack/Tutorial_3/vue-til-server/dist/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/naver/.npm/_logs/2020-06-17T08_02_06_763Z-debug.log
```
- node -v 확인시
```
naver@noah-macbook vue-til-server % node -v
v10.16.0
naver@noah-macbook vue-til-server % 
```

**Comment by noah6netguy** [comment]
사전에 준비해보고자하는데...  도움 받을수 있을까요..?

**Comment by joshua1988** [comment]
@noah6netguy 안녕하세요 노아님, 제가 업무 때문에 너무 정신이 없어서 이제서야 확인했네요 ㅜㅜ

**Comment by noah6netguy** [comment]
아 감사합니다.
node_modules 에 대해 사용자 권한이 root로 되어있었던 부분을 mac 사용자로 변경 후 

정상 동작합니다. 감사합니다.
